In [3]:
pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.10.1-py3-none-any.whl (226 kB)
     ------------------------------------ 226.0/226.0 kB 337.1 kB/s eta 0:00:00
Requirement already satisfied: joblib>=1.1.1 in d:\datascience\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in d:\datascience\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.21.5)
Requirement already satisfied: scikit-learn>=1.0.2 in d:\datascience\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.2.1)
Requirement already satisfied: scipy>=1.3.2 in d:\datascience\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.9.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\datascience\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (2.2.0)
Installing collected packages: imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.10.1 imblearn-0.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.2.12-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: scikit-learn in d:\datascience\anaconda3\lib\site-packages (from lazypredict) (1.2.1)
Requirement already satisfied: click in d:\datascience\anaconda3\lib\site-packages (from lazypredict) (8.0.4)
Collecting lightgbm
  Downloading lightgbm-3.3.5-py3-none-win_amd64.whl (1.0 MB)
     ---------------------------------------- 1.0/1.0 MB 1.0 MB/s eta 0:00:00
Requirement already satisfied: xgboost in c:\users\lenovo\appdata\roaming\python\python39\site-packages (from lazypredict) (1.7.2)
Requirement already satisfied: joblib in d:\datascience\anaconda3\lib\site-packages (from lazypredict) (1.2.0)
Requirement already satisfied: tqdm in d:\datascience\anaconda3\lib\site-packages (from lazypredict) (4.64.1)
Requirement already satisfied: pandas in d:\datascience\anaconda3\lib\site-packages (from lazypredict) (1.4.4)
Requirement already satisfied: colorama in d:\datascience\anaconda3\lib\site-packages (from click->lazypredict) (0.4.5)
Requirement already satisfied: wheel in d:\datascience\anaconda3\lib\site-packages (from lightgbm->lazypredict) (0.37.1)
Requirement already satisfied: scipy in d:\datascience\anaconda3\lib\site-packages (from lightgbm->lazypredict) (1.9.1)
Requirement already satisfied: numpy in d:\datascience\anaconda3\lib\site-packages (from lightgbm->lazypredict) (1.21.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\datascience\anaconda3\lib\site-packages (from scikit-learn->lazypredict) (2.2.0)
Requirement already satisfied: pytz>=2020.1 in d:\datascience\anaconda3\lib\site-packages (from pandas->lazypredict) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in d:\datascience\anaconda3\lib\site-packages (from pandas->lazypredict) (2.8.2)
Requirement already satisfied: six>=1.5 in d:\datascience\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->lazypredict) (1.16.0)
Installing collected packages: lightgbm, lazypredict
Successfully installed lazypredict-0.2.12 lightgbm-3.3.5
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import recall_score 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

from sklearn.tree import DecisionTreeClassifier

from imblearn.combine import SMOTEENN

In [7]:
df = pd.read_csv('tel_churn.csv')

In [8]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,1,0,0,1,1,...,0,0,1,0,1,0,0,0,0,0
1,1,0,56.95,1889.50,0,0,1,1,0,1,...,0,0,0,1,0,0,1,0,0,0
2,2,0,53.85,108.15,1,0,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0
3,3,0,42.30,1840.75,0,0,1,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,4,0,70.70,151.65,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0

In [11]:
df = df.drop('Unnamed: 0', axis=1)

In [12]:
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,0,1,1,0,1,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,1,0,1,1,0,1,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0

In [14]:
#Creating x and y variables
x = df.drop('Churn', axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,1,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,1,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,0,1,1,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,1,1,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,0,1,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
7028,0,103.20,7362.90,1,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,1
7029,0,29.60,346.45,1,0,0,1,0,1,1,...,0,0,1,0,1,0,0,0,0,0
7030,1,74.40,306.60,0,1,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
7031,0,105.65,6844.50,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1

In [15]:
y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

***Decision Tree Classifier***

In [17]:
model_dt = DecisionTreeClassifier(criterion='gini',random_state=100, max_depth=6, min_samples_leaf=8)

In [18]:
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [19]:
y_pred = model_dt.predict(x_test)

In [20]:
y_pred

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

In [24]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1026
           1       0.66      0.49      0.56       381

    accuracy                           0.79      1407
   macro avg       0.74      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [25]:
print(confusion_matrix(y_test, y_pred))

[[928  98]
 [194 187]]

In [33]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x,y)

In [34]:
xr_train, xr_test, yr_train, yr_test = train_test_split(x_resampled,y_resampled, test_size=0.2)

In [36]:
model_dt_smote = DecisionTreeClassifier(criterion = 'gini', random_state=100, max_depth=6, min_samples_leaf=8)

In [37]:
model_dt_smote.fit(xr_train, yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [38]:
y_pred_smote = model_dt_smote.predict(xr_test)

In [39]:
print(classification_report(yr_test, y_pred_smote, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.94      0.91      0.92       527
           1       0.93      0.95      0.94       640

    accuracy                           0.93      1167
   macro avg       0.93      0.93      0.93      1167
weighted avg       0.93      0.93      0.93      1167

In [41]:
print(confusion_matrix(yr_test, y_pred_smote))

[[478  49]
 [ 29 611]]

**RANDOM FOREST CLASSIFIER**

In [46]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)
model_rf.fit(x_train, y_train)
y_pred_rf = model_rf.predict(x_test)

In [47]:
print(classification_report(y_test, y_pred_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.93      0.88      1026
           1       0.72      0.46      0.56       381

    accuracy                           0.81      1407
   macro avg       0.77      0.70      0.72      1407
weighted avg       0.80      0.81      0.79      1407

In [48]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x,y)

In [56]:
xr_train, xr_test, yr_train, yr_test = train_test_split(x_resampled,y_resampled, test_size=0.2)
model_smote_rf = RandomForestClassifier(n_estimators=100,criterion = 'gini', random_state=100, max_depth=6, min_samples_leaf=8)
model_smote_rf.fit(xr_train, yr_train)
y_pred_smote_rf = model_smote_rf.predict(xr_test)
print(classification_report(yr_test, y_pred_smote, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.42      0.42      0.42       506
           1       0.55      0.54      0.55       655

    accuracy                           0.49      1161
   macro avg       0.48      0.48      0.48      1161
weighted avg       0.49      0.49      0.49      1161

In [57]:
print(confusion_matrix(yr_test, y_pred_smote_rf, labels=[0,1]))

[[447  59]
 [ 16 639]]

**SAVE THE MODEL**

In [58]:
import pickle

In [59]:
filename='model.sav'
pickle.dump(model_smote_rf, open(filename, 'wb'))

In [60]:
load_model = pickle.load(open(filename, 'rb'))

In [61]:
load_model.score(xr_test, yr_test)

0.9354005167958657